name: Bug Report
description: File a bug report
labels: ["Bug"]
assignees:
  - TheClassic36
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    id: modversion
    attributes:
      label: Mod Version
      description: Which version of Revert DAF Sounds are you using? If the version you are running is not listed, please update first.
      options:
        - v1.2.1
        - v1.2.0
        - v1.1.0
        - v1.0.3
    validations:
      required: true
  - type: textarea
    id: etsversion
    attributes:
      label: ETS2 Version
      description: Which version of Euro Truck Simulator 2 are you using?
      placeholder: This can be found in the bottom right corner of the "launchpad" in-game (before you select a profile)
    validations:
      required: true